/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225703;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BoardTest {
    @Test 
    void initializeTest() {
        String white = "⚪️";

        Board testBoard = new Board();
        testBoard.initialize();
        assertEquals(testBoard.board[3][3], white);
    }
}
